FROM mcr.microsoft.com/dotnet/core/sdk:3.1.302-alpine3.12 as builder
EXPOSE 27017

COPY . .

RUN dotnet publish --configuration Release MembershipApi/MembershipApi.csproj -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.8-alpine3.12

WORKDIR /app

COPY --from=builder /app .

CMD ["dotnet", "MembershipApi.dll"]